package mmorpg.framework.spec;

public enum CombatStat {
    BASE_DAMAGE,
    SKILL_DAMAGE_PERCENT,
    CRIT_CHANCE,
    CRIT_DAMAGE,
    COMBO_MULTIPLIER,
    BACKSTAB_MULTIPLIER,
    WEAK_POINT_DAMAGE,
    ARMOR,
    MAGIC_RESISTANCE,
    DAMAGE_MITIGATION_PERCENT,
    GUARD_STRENGTH,
    DODGE_CHANCE,
    BLOCK_VALUE,
    ATTACK_SPEED,
    CAST_SPEED,
    COOLDOWN_REDUCTION,
    GLOBAL_COOLDOWN,
    MOVEMENT_SPEED,
    TURN_PRIORITY
}
