package mmorpg.framework.spec;

public enum SecondaryStat {
    PHYSICAL_POWER,
    ARMOR_PENETRATION,
    ATTACK_SPEED,
    ACCURACY,
    EVASION,
    WEAPON_HANDLING,
    CRIT_DAMAGE_PERCENT,
    SPELL_POWER,
    ELEMENTAL_MASTERY,
    CAST_SPEED,
    MAGIC_PENETRATION,
    MANA_EFFICIENCY,
    OVERCHARGE_PERCENT,
    MAX_HP,
    HP_REGEN,
    SHIELD_STRENGTH,
    DAMAGE_REDUCTION_PERCENT,
    BLOCK_CHANCE,
    PARRY_CHANCE
}
